name: (MAIN)Auto Deploy to S3 Bucket & Cloudfront Invalidate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: (MAIN)Auto Deploy to S3 Bucket
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: NPM install
        run: npm install

      - name: NPM Build
        run: npm run build

      - name: Transfer to S3 for serving static
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_S3_BUCKET_REGION }}
          SOURCE_DIR: 'build'
