name: (MAIN)Auto Deploy to S3 Bucket & Cloudfront Invalidate

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: (MAIN)Auto Deploy to S3 Bucket
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codes
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: .env setting
        run: |
          echo "REACT_APP_BACKEND_API_URL=${{ secrets.REACT_APP_BACKEND_API_URL }}" >> .env
          echo "REACT_APP_KAKAO_REST_API_KEY=${{ secrets.REACT_APP_KAKAO_REST_API_KEY }}" >> .env
          echo "REACT_APP_PRD_REDIRECT_URI=${{ secrets.REACT_APP_PRD_REDIRECT_URI }}" >> .env

      - name: NPM install
        run: npm install

      - name: NPM Build
        run: npm run build

      - name: Sync files to S3
        run: |
          aws s3 sync $SOURCE_DIR s3://${{ secrets.AWS_S3_BUCKET_NAME }} --acl public-read --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_S3_BUCKET_REGION }}
          SOURCE_DIR: 'build'
