name: (MAIN)Auto Deploy to S3 Bucket & Cloudfront Invalidate

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: (MAIN)Auto Deploy to S3 Bucket & Cloudfront Invalidate
    runs-on: ubuntu-latest

    steps:
      - name: git clone
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: npm install
        run: npm install

      - name: npm build
        run: npm run build

      - name: deploy
        env:
          AWS_ACCESS_KEY_ID: '$'
          AWS_SECRET_ACCESS_KEY: '$'
        run: aws s3 cp --recursive --region ap-northeast-2 dist s3://seninanum
